package com.xiyunmn.puredupan.hook.ui

object UiText {
    object Settings {
        const val MODULE_SETTINGS = "设置"
        const val BRAND_TAG = "PureDuPan"

        const val GROUP_CONTENT_BLOCK = "内容屏蔽"
        const val GROUP_UI_OPTIMIZE = "UI净化"
        const val GROUP_THEME = "拓展功能"
        const val GROUP_DEBUG = "调试"

        const val BLOCK_SPLASH_INTERSTITIAL_LABEL = "去除开屏、热重载广告"
        const val BLOCK_SPLASH_INTERSTITIAL_DESC = "拦截冷启动时开屏与切屏时热重载广告"
        const val REMOVE_HOT_START_SPLASH_LABEL = "移除切屏加载"
        const val REMOVE_HOT_START_SPLASH_DESC = "启用 DexKit 解析后生效\n拦截切回前台或熄屏解锁时拉起的启动图"
        const val BLOCK_IN_APP_DIALOG_LABEL = "屏蔽应用内弹窗"
        const val BLOCK_IN_APP_DIALOG_DESC = "拦截网盘运行期间弹出的运营浮窗、幸运券包等活动弹窗"
        const val BLOCK_UPDATE_DIALOG_LABEL = "屏蔽软件更新"
        const val BLOCK_UPDATE_DIALOG_DESC = "拦截网盘内弹出的新版本更新提示窗口"
        const val BLOCK_FULL_SCREEN_BACKUP_LABEL = "屏蔽全屏弹窗"
        const val BLOCK_FULL_SCREEN_BACKUP_DESC = "拦截网盘弹出的全屏图文/视频安全备份引导、SVIP专属图标等页面"
        const val BLOCK_SHARE_PUSH_GUIDE_LABEL = "屏蔽「共享」页面推送提醒"
        const val BLOCK_SHARE_PUSH_GUIDE_DESC = "拦截切换到「共享」页面时弹出的开启推送通知半屏引导对话框"
        const val BLOCK_APP_STORE_REVIEW_LABEL = "屏蔽评分弹窗"
        const val BLOCK_APP_STORE_REVIEW_DESC = "去除切换到「文件」页面时弹出的评分引导弹窗"
        const val BLOCK_NON_WIFI_DOWNLOAD_DIALOG_LABEL = "移除下载 WiFi 未连接弹窗"
        const val BLOCK_NON_WIFI_DOWNLOAD_DIALOG_DESC = "未连接 WiFi 时点击下载，自动确认并直接创建下载任务"
        const val BLOCK_NOTIFICATION_PROMPT_LABEL = "移除消息通知弹窗"
        const val BLOCK_NOTIFICATION_PROMPT_DESC = "拦截启动时系统通知权限请求和应用内消息通知引导弹窗"

        const val HIDE_HOME_TOP_PROMOTION_LABEL = "顶部动态推广"
        const val HIDE_HOME_TOP_PROMOTION_DESC = "隐藏「首页」顶部搜索框区域的动态推广，并跳过对应启动期预加载"
        const val HOME_CUSTOMIZE_LABEL = "首页定制"
        const val HOME_CUSTOMIZE_DESC = "管理「首页」顶部搜索框、动态推广和推荐提示"
        const val HIDE_HOME_SEARCH_PLACEHOLDER_LABEL = "搜索框提示词"
        const val HIDE_HOME_SEARCH_PLACEHOLDER_DESC = "隐藏首页搜索框内滚动提示词（title_bar_search_place_holder_text）"
        const val HIDE_HOME_SEARCH_AIGC_ICON_LABEL = "搜索框 AIGC 图标"
        const val HIDE_HOME_SEARCH_AIGC_ICON_DESC = "隐藏首页搜索框右侧 AIGC 图标（searchbox_aigc_icon）"
        const val HIDE_HOME_FEED_TIP_LABEL = "开启推荐提示"
        const val HIDE_HOME_FEED_TIP_DESC = "隐藏首页信息流上方「开启推荐」提示条（cl_feed_tip）"
        const val HIDE_HOME_BANNER_LABEL = "轮播图广告"
        const val HIDE_HOME_BANNER_DESC = "隐藏首页信息流头部轮播图广告区域（headerBanner / newhome_header_type_banner）"
        const val HIDE_HOME_MEMORIES_SECTION_LABEL = "回忆"
        const val HIDE_HOME_MEMORIES_SECTION_DESC = "隐藏首页信息流头部「回忆」板块（HomeStoryCardView）"
        const val HIDE_HOME_SAVE_SECTION_LABEL = "转存"
        const val HIDE_HOME_SAVE_SECTION_DESC = "隐藏首页信息流头部「转存」板块（NewHomeSaveCardView）"
        const val HIDE_HOME_RECENT_SECTION_LABEL = "最近"
        const val HIDE_HOME_RECENT_SECTION_DESC = "隐藏首页信息流头部「最近」板块（NewHomeRecentCardView）"
        const val REMOVE_GAME_CENTER_LABEL = "游戏中心"
        const val REMOVE_GAME_CENTER_DESC = "隐藏「我的」游戏中心入口"
        const val REMOVE_ABOUT_ME_BANNER_LABEL = "横幅广告"
        const val REMOVE_ABOUT_ME_BANNER_DESC = "隐藏「我的」底部横幅推广区域"
        const val REMOVE_MY_SERVICE_LABEL = "服务入口"
        const val REMOVE_MY_SERVICE_DESC = "隐藏「我的」服务入口"
        const val HIDE_ABOUT_ME_COIN_CENTER_BUBBLE_LABEL = "任务中心奖励悬浮球"
        const val HIDE_ABOUT_ME_COIN_CENTER_BUBBLE_DESC = "隐藏「我的」页任务中心/金币中心奖励悬浮球（v_bubble）"
        const val HIDE_ABOUT_ME_SIGN_IN_DOT_LABEL = "右上角签到小红点"
        const val HIDE_ABOUT_ME_SIGN_IN_DOT_DESC = "隐藏「我的」页右上角签到入口旁的小红点（f1_entry_dot）"
        const val HIDE_ABOUT_ME_AI_COIN_ASSET_LABEL = "AI 点数和资产"
        const val HIDE_ABOUT_ME_AI_COIN_ASSET_DESC = "隐藏会员卡片下方 AI 点数和资产区域（layout_ai_coin），可减少卡片底部占用"
        const val SHARE_PAGE_CUSTOMIZE_LABEL = "共享页定制"
        const val SHARE_PAGE_CUSTOMIZE_DESC = "管理「共享」页面右下角广告悬浮窗"
        const val REMOVE_HOME_FAB_LABEL = "广告悬浮窗"
        const val REMOVE_HOME_FAB_DESC = "移除「共享」页面右下角广告悬浮球"
        const val HIDE_RENEW_BUTTON_LABEL = "续费提示"
        const val HIDE_RENEW_BUTTON_DESC = "隐藏「我的」向下滑动时出现的去续费按钮"
        const val BLOCK_BOTTOM_BADGE_LABEL = "移除底栏「共享」红色角标"
        const val BLOCK_BOTTOM_BADGE_DESC = "移除底部导航栏「共享」右上角出现的红色数字角标"
        const val BLOCK_ALBUM_BACKUP_BAR_LABEL = "移除照片备份浮窗"
        const val BLOCK_ALBUM_BACKUP_BAR_DESC = "移除「文件」页面底部“开启照片自动备份”引导条"
        const val REPLACE_MEMBER_CARD_BACKGROUND_LABEL = "更换会员卡背景"
        const val REPLACE_MEMBER_CARD_BACKGROUND_DESC = "使用系统相册图片替换会员卡背景；建议图片尺寸约 1080×360 或同等 3:1 横图，过小图片可能模糊"
        const val MEMBER_CARD_BACKGROUND_PICK = "选择图片"
        const val MEMBER_CARD_BACKGROUND_NONE = "未选择"
        const val MEMBER_CARD_BACKGROUND_CHOOSE = "选择"
        const val MEMBER_CARD_BACKGROUND_ADJUST = "调整"
        const val MEMBER_CARD_BACKGROUND_CLEAR = "清除"
        const val MEMBER_CARD_BACKGROUND_PICKED = "会员卡背景图片已选择"
        const val MEMBER_CARD_BACKGROUND_PICK_FAILED = "无法打开系统相册"
        const val MEMBER_CARD_BACKGROUND_CLEAR_LABEL = "清除自定义图片"
        const val MEMBER_CARD_BACKGROUND_CLEAR_DESC = "移除已选择的会员卡背景图片，保存后恢复宿主默认背景"
        const val MEMBER_CARD_BACKGROUND_CLEAR_PENDING = "保存后将恢复默认会员卡背景"
        const val MEMBER_CARD_BACKGROUND_BLUR_LABEL = "背景模糊度"
        const val MEMBER_CARD_BACKGROUND_BLUR_DESC = "给自定义背景添加模糊，0 为不模糊"
        const val MEMBER_CARD_BACKGROUND_BLUR_NONE = "无"
        const val MEMBER_CARD_BACKGROUND_EDITOR_TITLE = "调整会员卡背景"
        const val MEMBER_CARD_BACKGROUND_EDITOR_HINT = "完整图片会显示在候选框外，拖动图片到候选框内，双指缩放或使用滑条微调显示区域"
        const val MEMBER_CARD_BACKGROUND_SCALE_LABEL = "缩放"
        const val MEMBER_CARD_BACKGROUND_ROTATE = "旋转"
        const val MEMBER_CARD_BACKGROUND_EDITOR_SAVED = "会员卡背景显示区域已保存"
        const val MEMBER_CARD_BACKGROUND_EDITOR_FAILED = "无法读取会员卡背景图片"
        const val MEMBER_CARD_BACKGROUND_SAVE_TO_ALBUM = "保存到相册"
        const val MEMBER_CARD_BACKGROUND_SAVED_TO_ALBUM = "图片已保存到相册"
        const val MEMBER_CARD_BACKGROUND_SAVE_TO_ALBUM_FAILED = "保存图片失败"
        const val MEMBER_CARD_SIZE_ADJUST_LABEL = "调整会员卡片尺寸"
        const val MEMBER_CARD_SIZE_ADJUST_DESC = "调整会员卡片背景视图宽高；0 表示使用宿主默认尺寸"
        const val MEMBER_CARD_WIDTH_LABEL = "会员卡片宽度"
        const val MEMBER_CARD_SIZE_HEIGHT_LABEL = "会员卡片高度"
        const val MEMBER_CARD_SIZE_DEFAULT = "默认"
        const val HIDE_MEMBER_CARD_OPERATION_LABEL = "会员卡片活动入口"
        const val HIDE_MEMBER_CARD_OPERATION_DESC = "隐藏会员卡片右上角运营活动入口；该入口来自会员卡运营位下发，当前使用本页视图级隐藏，不影响会员信息展示"
        const val HIDE_MEMBER_CARD_BENEFIT_LABEL = "等级福利"
        const val HIDE_MEMBER_CARD_BENEFIT_DESC = "隐藏会员卡片权益区最后一个等级福利入口，保留其它权益格"
        const val HIDE_MEMBER_CARD_FIRST_BENEFIT_LABEL = "等级福利卡片 1"
        const val HIDE_MEMBER_CARD_FIRST_BENEFIT_DESC = "隐藏会员卡片第一张等级福利卡片（cl_first_card）"
        const val HIDE_MEMBER_CARD_SECOND_BENEFIT_LABEL = "等级福利卡片 2"
        const val HIDE_MEMBER_CARD_SECOND_BENEFIT_DESC = "隐藏会员卡片第二张等级福利卡片（cl_second_card）"
        const val HIDE_MEMBER_CARD_THIRD_BENEFIT_LABEL = "专属权益"
        const val HIDE_MEMBER_CARD_THIRD_BENEFIT_DESC = "隐藏会员卡片第三张专属权益卡片（cl_third_card）；当等级福利与专属权益同时隐藏时，会一并隐藏分隔线（view_line）"
        const val HIDE_MEMBER_CARD_BENEFIT_BAR_LABEL = "权益栏"
        const val HIDE_MEMBER_CARD_BENEFIT_BAR_DESC = "隐藏会员卡片中部的权益图标栏（ll_root）"
        const val HIDE_MEMBER_CARD_SVIP_LEVEL_LABEL = "SVIP 等级"
        const val HIDE_MEMBER_CARD_SVIP_LEVEL_DESC = "隐藏会员卡片标题旁的 SVIP 等级图标（iv_vip_image）"
        const val HIDE_MEMBER_CARD_SVIP_STATUS_LABEL = "SVIP 权益尊享中"
        const val HIDE_MEMBER_CARD_SVIP_STATUS_DESC = "隐藏会员卡片内的权益状态文案（tv_duration_content）"
        const val HIDE_MEMBER_CARD_RENEW_BUTTON_LABEL = "续费按钮"
        const val HIDE_MEMBER_CARD_RENEW_BUTTON_DESC = "隐藏会员卡片内的立即续费/开通按钮，不影响等级和到期时间展示"
        const val HIDE_INTL_MEMBER_CARD_SVIP_LEVEL_LABEL = "SVIP等级"
        const val HIDE_INTL_MEMBER_CARD_SVIP_LEVEL_DESC = "隐藏会员卡片顶部的 SVIP 等级徽标（iv_vip_image）"
        const val HIDE_INTL_MEMBER_CARD_UPGRADE_BUTTON_LABEL = "升级按钮"
        const val HIDE_INTL_MEMBER_CARD_UPGRADE_BUTTON_DESC = "隐藏会员卡片右上角的“去升级”按钮（tv_enter）"
        const val MEMBER_CARD_CUSTOMIZE_LABEL = "会员卡片定制"
        const val REMOVE_MEMBER_CARD_CLICK_LABEL = "移除卡片点击跳转"
        const val REMOVE_MEMBER_CARD_CLICK_DESC = "移除点击会员卡片跳转「我的会员/续费」的事件，不影响卡片内容展示"
        const val VIEW_MEMBER_CARD_BACKGROUND_ON_CLICK_LABEL = "点击卡片查看背景图片"
        const val VIEW_MEMBER_CARD_BACKGROUND_ON_CLICK_DESC = "将会员卡片点击事件替换为查看当前自定义背景图片；需先选择并启用会员卡背景"
        const val MEMBER_CARD_CUSTOMIZE_DESC = "管理「我的」页会员卡片背景、点击事件、运营活动入口、等级福利和续费按钮"
        const val REPLACE_BOTTOM_AI_LABEL = "底栏AI替换为「会员」"
        const val REPLACE_BOTTOM_AI_DESC = "将底部导航栏的AI入口替换为「会员」"
        const val MY_PAGE_CUSTOMIZE_LABEL = "我的页定制"
        const val MY_PAGE_CUSTOMIZE_DESC = "管理「我的」页面中的续费提示、游戏中心、横幅广告与服务入口"
        const val CUSTOM_BOTTOM_BAR_LABEL = "底栏定制"
        const val CUSTOM_BOTTOM_BAR_DESC = "自定义隐藏底部导航栏中的指定 Tab"

        const val FOLLOW_SYSTEM_NIGHT_MODE_LABEL = "夜间模式跟随系统"
        const val FOLLOW_SYSTEM_NIGHT_MODE_DESC = "接管宿主换肤机制，使宿主界面主题与系统主题实时同步"
        const val PERFORMANCE_OPTIMIZE_LABEL = "性能优化"
        const val PERFORMANCE_OPTIMIZE_DESC = "可能造成功能异常，谨慎启用"
        const val PERFORMANCE_OPTIMIZE_DIALOG_TITLE = "性能优化"
        const val PERFORMANCE_OPTIMIZE_SAVED = "性能优化配置已保存"
        const val ACCELERATE_INTL_SPLASH_STARTUP_LABEL = "加速开屏启动"
        const val ACCELERATE_INTL_SPLASH_STARTUP_DESC = "减少启动图停留时间，移除过渡动画"
        const val DETAILED_LOGGING_LABEL = "输出详细日志"
        fun detailedLoggingDesc(hostPackageName: String): String =
            "输出更详细的 Hook调试日志，日志通常位于宿主应用缓存目录下：" +
                "/data/user/0/$hostPackageName/cache/wangpanhook/logs/"
        const val EXPERIMENTAL_DEXKIT_LABEL = "启用 DexKit 实验解析"
        const val EXPERIMENTAL_DEXKIT_DESC = "启用DexKit 解析链路，部分功能依赖"
        const val DEXKIT_STATUS_TITLE = "DexKit 查询状态"
        const val DEXKIT_STATUS_SUMMARY_PREFIX = "成功数/总数"
        const val DEXKIT_STATUS_TARGET = "目标"
        const val DEXKIT_STATUS_FEATURE = "对应功能"
        const val DEXKIT_STATUS_PENDING = "待扫描"
        const val DEXKIT_STATUS_SCANNING = "扫描中"
        const val DEXKIT_STATUS_SUCCESS = "成功"
        const val DEXKIT_STATUS_NOT_FOUND = "未找到"
        const val DEXKIT_STATUS_ERROR = "失败"
        const val CLEAR_LOGS_LABEL = "清理日志"
        const val CLEAR_LOGS_DESC = "删除宿主应用缓存目录下的模块日志文件"
        const val CLEAR_LOGS_CONFIRM_TITLE = "清理日志"
        const val CLEAR_LOGS_CONFIRM_MESSAGE = "将删除 APP 缓存目录中的模块日志文件。"
        const val CLEAR_LOGS_SUCCESS = "日志已清理"
        const val CLEAR_LOGS_FAILED = "部分日志清理失败"
        const val RESET_MODULE_SETTINGS_LABEL = "重置模块设置"
        const val RESET_MODULE_SETTINGS_DESC = "清空模块保存的配置并恢复默认选项，确认后将重启百度网盘"
        const val RESET_MODULE_SETTINGS_CONFIRM_TITLE = "重置模块设置"
        const val RESET_MODULE_SETTINGS_CONFIRM_MESSAGE = "将清空 PureDuPan 模块配置并恢复默认选项。"
        const val RESET_MODULE_SETTINGS_SUCCESS = "模块设置已重置，正在重启百度网盘"
        const val RESET_MODULE_SETTINGS_FAILED = "模块设置重置失败"
        const val PERFORMANCE_GROUP_POST_INIT = "启动后置初始化"
        const val PERFORMANCE_GROUP_STARTUP_PREFETCH = "启动异步预取"
        const val PERFORMANCE_GROUP_RUNTIME_SERVICE = "运行时服务/进程唤起"
        const val PERFORMANCE_GROUP_AD_INCENTIVE = "广告与激励链路"
        const val PERFORMANCE_GROUP_INTL_STARTUP_DELAY = "启动期延后"
        const val DISABLE_GARBAGE_CLEAN_SERVICE_REGISTER_LABEL = "清理组件服务注册"
        const val DISABLE_GARBAGE_CLEAN_SERVICE_REGISTER_DESC = "跳过启动后置阶段的清理组件服务注册，不删除清理数据或缓存"
        const val DISABLE_DATAPACK_SOCKET_REGISTER_LABEL = "流量包权益 Socket 注册"
        const val DISABLE_DATAPACK_SOCKET_REGISTER_DESC = "跳过启动后置阶段的流量包权益变化 Socket 注册，不影响其它 Socket 业务"
        const val DISABLE_AIGC_BACKGROUND_COMPONENT_LABEL = "AIGC 小组件后台刷新"
        const val DISABLE_AIGC_BACKGROUND_COMPONENT_DESC = "阻止 AIGC 小组件后台刷新和资源解压，不拦截用户主动打开 AI 页面"
        const val DISABLE_DYNAMIC_PLUGIN_AUTO_DOWNLOAD_LABEL = "边缘动态插件自动下载/安装"
        const val DISABLE_DYNAMIC_PLUGIN_AUTO_DOWNLOAD_DESC = "阻止 OCR、图片转 Office、识图、人脸检测等边缘插件后台自动下载/安装，不删除已安装插件"
        const val DISABLE_OEM_PUSH_SERVICE_LABEL = "OEM 厂商推送组件唤起"
        const val DISABLE_OEM_PUSH_SERVICE_DESC = "阻止华为/荣耀/小米/OPPO/VIVO/魅族推送组件在主进程或宿主推送进程中被唤起，保留系统下载通知"
        const val DISABLE_VIDEO_AD_PRELOAD_LABEL = "视频前贴广告素材预下载"
        const val DISABLE_VIDEO_AD_PRELOAD_DESC = "阻止前后台切回时预下载视频前贴广告素材，不影响普通视频播放链路"
        const val DISABLE_AD_SDK_INIT_LABEL = "广告 SDK 下载服务"
        const val DISABLE_AD_SDK_INIT_DESC = "阻止 GDT/Pangle/BeiZi/UBiX/Octopus 广告下载服务启动，保留网盘下载服务"
        const val DISABLE_SWAN_PRELOAD_LABEL = "Swan 小程序运行时预加载"
        const val DISABLE_SWAN_PRELOAD_DESC = "阻止启动后提前拉起小程序运行时，手动打开相关页面时仍按需加载但可能变慢"
        const val DISABLE_THUMBNAIL_OPERATOR_SERVICE_LABEL = "缩略图端计算任务"
        const val DISABLE_THUMBNAIL_OPERATOR_SERVICE_DESC = "阻止端计算管理器初始化和缩略图任务提交；开启后新上传图片、相册或云端缩略图生成/刷新可能变慢"
        const val DISABLE_INCENTIVE_BUSINESS_SERVICE_LABEL = "激励业务服务"
        const val DISABLE_INCENTIVE_BUSINESS_SERVICE_DESC = "阻止激励任务、看广告领权益、广告应用下载与相关统计服务启动；开启后这些活动可能不再可用"
        const val DISABLE_MEDIA_BROWSER_SERVICE_AUTOSTART_LABEL = "音频媒体服务自启动"
        const val DISABLE_MEDIA_BROWSER_SERVICE_AUTOSTART_DESC = "阻止启动期拉起 NetdiskMediaBrowserService 音频媒体服务；手动打开音频仍按需启动。警告：蓝牙、车机、系统媒体浏览和锁屏媒体控制的自动连接可能失效"
        const val DISABLE_ICON_RESOURCE_DOWNLOAD_LABEL = "图标资源启动下载"
        const val DISABLE_ICON_RESOURCE_DOWNLOAD_DESC = "阻止启动异步阶段下载运营和文件类型图标资源；已缓存图标不会删除，个别新图标可能显示默认样式"
        const val DISABLE_B2F_GUIDANCE_PREFETCH_LABEL = "B2F 引导数据启动预拉取"
        const val DISABLE_B2F_GUIDANCE_PREFETCH_DESC = "阻止启动异步阶段预拉取回流引导和运营弹窗数据；不清理引导状态，相关弹窗可能减少或按需变慢"
        const val BLOCK_INTL_OFFLINE_PACKAGE_INIT_LABEL = "阻止 H5 离线包初始化"
        const val BLOCK_INTL_OFFLINE_PACKAGE_INIT_DESC = "启动期阻止 H5 离线包配置监听和自动下载队列初始化；进入 H5/离线包页面前按需恢复"
        const val DELAY_INTL_FEED_PRELOAD_LABEL = "延后首页 Feed 预加载"
        const val DELAY_INTL_FEED_PRELOAD_DESC = "启动期先跳过首页 Feed 预加载，首页稳定后用原参数自动恢复，手动刷新与后续加载不拦截"
        const val DELAY_INTL_TASK_SCORE_REFRESH_LABEL = "延后任务积分刷新"
        const val DELAY_INTL_TASK_SCORE_REFRESH_DESC = "启动期先跳过任务积分/会员频道的非强制刷新，首页稳定后或进入会员任务入口前自动恢复；强制刷新不拦截"
        const val BLOCK_INTL_STORY_DOUYIN_INIT_LABEL = "阻止 Story/DouYin 初始化"
        const val BLOCK_INTL_STORY_DOUYIN_INIT_DESC = "启用 DexKit 解析后生效\n启动期阻止 Story 视频预加载、Story UI 服务与 DouYin SDK 初始化；进入 Story/短视频或 DouYin 分享/授权入口时按需恢复"
        const val DELAY_INTL_NON_CORE_DIFF_SOCKET_LABEL = "延后非核心 diff socket 注册"
        const val DELAY_INTL_NON_CORE_DIFF_SOCKET_DESC = "启动期延后云图、云视频、搜索 diff socket 注册，保留核心文件 diff；首页稳定后或进入对应入口前恢复"
        const val DELAY_INTL_FLOAT_VIEW_STARTUP_LABEL = "延后浮层初始化"
        const val DELAY_INTL_FLOAT_VIEW_STARTUP_DESC = "启动期延后任务提示、音频圈容器和第三方返回提示的生命周期注册；首页稳定后或进入对应入口前恢复"
        const val BLOCK_INTL_AUDIO_CIRCLE_STARTUP_SHOW_LABEL = "阻止启动期音频圈自动显示"
        const val BLOCK_INTL_AUDIO_CIRCLE_STARTUP_SHOW_DESC = "首页稳定前阻止无播放源的音频圈显示请求；主动进入音频/播放入口和已有播放源不拦截"
        const val BLOCK_INTL_AIGC_WIDGET_BACKGROUND_LABEL = "阻止 AIGC Widget 后台刷新"
        const val BLOCK_INTL_AIGC_WIDGET_BACKGROUND_DESC = "阻止 AIGC 小组件后台刷新和资源解压，不拦截用户主动打开 AI 页面"
        const val BLOCK_INTL_ALBUM_AI_INIT_LABEL = "阻止相册 AI 初始化"
        const val BLOCK_INTL_ALBUM_AI_INIT_DESC = "启动期阻止相册 AI/NLP/AILab 初始化；进入 AI 面板、AI 搜图、NLP 预览或 AILab 入口时按需恢复"
        const val ACTION_ICON_SETTINGS = "⚙"
        const val ACTION_ICON_GALLERY = "相册"
        const val ACTION_ICON_CLEAR = "清除"
        const val ACTION_ICON_RESET = "重置"
        const val BOTTOM_BAR_DIALOG_TITLE = "底栏定制"
        const val CUSTOM_HIDE_TEXT_WIDGET_SECTION_TITLE = "自定义隐藏控件文本"
        const val HIDE_ABOUT_ME_MANAGE_SPACE_TEXT_LABEL = "管理空间"
        const val HIDE_ABOUT_ME_MANAGE_SPACE_TEXT_DESC = "隐藏「我的」页中的“管理空间”控件文本入口"
        const val HIDE_ABOUT_ME_REWARD_TEXT_LABEL = "领奖励"
        const val HIDE_ABOUT_ME_REWARD_TEXT_DESC = "隐藏「我的」页中的“领奖励”控件文本入口"
        const val HIDE_ABOUT_ME_ACCOUNT_EXIT_TEXT_LABEL = "账号、退出"
        const val HIDE_ABOUT_ME_ACCOUNT_EXIT_TEXT_DESC = "隐藏「设置与服务」里的“账号、退出”控件文本入口"
        const val HIDE_ABOUT_ME_STAR_SKIN_TEXT_LABEL = "明星皮肤上线啦"
        const val HIDE_ABOUT_ME_STAR_SKIN_TEXT_DESC = "隐藏「个性设置」里的“明星皮肤上线啦”控件文本入口"
        const val HIDE_ABOUT_ME_FREE_DATA_CARD_TEXT_LABEL = "免流量卡、领无限空间"
        const val HIDE_ABOUT_ME_FREE_DATA_CARD_TEXT_DESC = "隐藏「我的」页中的“免流量卡、领无限空间”控件文本入口"
        const val BOTTOM_BAR_TAB_SECTION_TITLE = "自定义隐藏底栏Tab"
        const val BOTTOM_BAR_HIDE_TAB_HOME_LABEL = "「首页」"
        const val BOTTOM_BAR_HIDE_TAB_FILE_LABEL = "「文件」"
        const val BOTTOM_BAR_HIDE_TAB_SHARE_LABEL = "「共享」"
        const val BOTTOM_BAR_HIDE_TAB_VIP_LABEL = "「会员」"
        const val BOTTOM_BAR_HIDE_TAB_AIGC_LABEL = "「AIGC」"
        const val BOTTOM_BAR_HIDE_TAB_MINE_LABEL = "「我的」"
        const val BOTTOM_BAR_AT_LEAST_ONE = "至少保留一个底部 Tab"
        const val BOTTOM_BAR_SAVED = "底栏定制配置已保存"
        const val SHARE_PAGE_CUSTOMIZE_DIALOG_TITLE = "共享页定制"
        const val SHARE_PAGE_CUSTOMIZE_SAVED = "共享页定制配置已保存"
        const val MY_PAGE_CUSTOMIZE_DIALOG_TITLE = "我的页定制"
        const val MY_PAGE_CUSTOMIZE_SAVED = "我的页定制配置已保存"
        const val HOME_CUSTOMIZE_DIALOG_TITLE = "首页定制"
        const val HOME_CUSTOMIZE_SAVED = "首页定制配置已保存"
        const val CUSTOM_HIDE_WIDGET_SECTION_TITLE = "自定义隐藏控件"
        const val CUSTOM_HIDE_SECTION_SECTION_TITLE = "自定义隐藏板块"
        const val MEMBER_CARD_CUSTOMIZE_DIALOG_TITLE = "会员卡片定制"
        const val MEMBER_CARD_CUSTOMIZE_SAVED = "会员卡片定制配置已保存"
        fun memberCardBackgroundSelected(name: String): String = "已选择：$name"

        const val ABOUT = "关于"
        const val VERSION = "版本"
        const val AUTHOR = "作者"
        const val AUTHOR_NAME = "xiyunmn"
        const val UNKNOWN = "未知"
        const val MODULE_DEBUG_VERSION = "Debug"
        const val MODULE_RELEASE_VERSION = "Release"

        const val SAVE = "保存"
        const val BUTTON_CANCEL = "取消"
        const val SAVE_AND_RESTART = "保存并重启"
        const val SETTINGS_SAVED_RESTARTING = "设置已保存，正在重启网盘"
        const val SETTINGS_SAVE_FAILED = "模块设置保存失败"
        private const val RESTART_HINT = "，重启网盘后生效"

        const val RESTRICTED_FEATURES_LOCKED_HINT = "高级功能已隐藏，连续点击版本号5次解锁"
        fun restrictedFeatureUnlockProgress(remaining: Int): String = "再点击 $remaining 次解锁高级功能"
        const val RESTRICTED_FEATURE_UNLOCKED_TEXT = "高级功能已解锁，正在重新打开设置面板"

        const val DISCLAIMER_TITLE = "免责声明"
        const val DISCLAIMER_MESSAGE = """本模块仅供学习与技术研究使用。

使用本模块可能导致应用异常、功能不可用、账号风险或其它不可预期后果。

作者不对使用本模块造成的任何后果承担责任。

点击"同意"即表示您已阅读并接受以上声明。"""

        const val RESTRICTED_FEATURE_WARNING_TITLE = "启用高级功能"
        const val RESTRICTED_FEATURE_WARNING_MESSAGE = """高级功能包含以下可选配置项：
• 首页定制
• 共享页定制
• 我的页定制
• 会员卡片定制
• 底栏定制
• 性能优化

注意事项：
1. 这些功能可能影响应用正常使用
2. 性能优化功能默认全部关闭，需逐项手动开启
3. 如遇异常请关闭对应功能

启用后这些功能将永久显示在设置面板中。"""

        fun disclaimerCountdown(seconds: Int): String = "同意 ($seconds)"
        fun restrictedFeatureWarningCountdown(seconds: Int): String = "启用 ($seconds)"

        const val BUTTON_DISAGREE = "拒绝"
        const val BUTTON_AGREE = "同意"
        const val BUTTON_ENABLE = "启用"
        const val DISCLAIMER_REJECTED = "已取消"

        fun withUnsupportedSuffix(label: String): String = "$label（暂不可用）"

        fun withPartialSuffix(label: String): String = "$label（部分可用）"

        fun withRestartHint(message: String): String = "$message$RESTART_HINT"

        fun aboutVersionSummary(
            hostName: String,
            hostBuildType: String,
            hostVersion: String,
            hostPackageName: String,
            moduleBuildType: String,
            moduleVersion: String,
        ): String {
            return "$hostName $hostVersion$hostBuildType $hostPackageName\n" +
                "模块 $moduleVersion$moduleBuildType"
        }
    }
}
