package com.xiyunmn.puredupan.hook.config

data class SettingsSnapshot(
    // Logging
    val isDetailedLoggingEnabled: Boolean = false,
    val isExperimentalDexKitEnabled: Boolean = false,

    // Splash / interstitial and dialog blocking
    val isSplashInterstitialBlockEnabled: Boolean = false,
    val isHotStartSplashRemoveEnabled: Boolean = false,
    val isInAppDialogBlocked: Boolean = false,
    val isUpdateDialogBlocked: Boolean = false,
    val isFullScreenBackupBlocked: Boolean = false,
    val isSharePushGuideBlocked: Boolean = false,
    val isAppStoreReviewBlocked: Boolean = false,

    // Host UI simplification
    val isBottomAiReplaced: Boolean = false,
    val isHomeCustomizeEnabled: Boolean = false,
    val isHomeTopPromotionHidden: Boolean = false,
    val isHomeSearchPlaceholderHidden: Boolean = false,
    val isHomeSearchAigcIconHidden: Boolean = false,
    val isHomeFeedTipHidden: Boolean = false,
    val isHomeBannerHidden: Boolean = false,
    val isHomeMemoriesSectionHidden: Boolean = false,
    val isHomeSaveSectionHidden: Boolean = false,
    val isHomeRecentSectionHidden: Boolean = false,
    val isSharePageCustomizeEnabled: Boolean = false,
    val isMyPageCustomizeEnabled: Boolean = false,
    val isGameCenterRemoved: Boolean = false,
    val isAboutMeBannerRemoved: Boolean = false,
    val isMyServiceRemoved: Boolean = false,
    val isAboutMeCoinCenterBubbleHidden: Boolean = false,
    val isAboutMeSignInDotHidden: Boolean = false,
    val isAboutMeManageSpaceTextHidden: Boolean = false,
    val isAboutMeRewardTextHidden: Boolean = false,
    val isAboutMeAccountExitTextHidden: Boolean = false,
    val isAboutMeStarSkinTextHidden: Boolean = false,
    val isAboutMeFreeDataCardTextHidden: Boolean = false,
    val isHomeFabRemoved: Boolean = false,
    val isRenewButtonHidden: Boolean = false,
    val isBottomBarBadgeBlocked: Boolean = false,
    val isAlbumBackupBarBlocked: Boolean = false,
    val isAboutMeAiCoinAssetHidden: Boolean = false,
    val isMemberCardCustomizeEnabled: Boolean = false,
    val isMemberCardBackgroundReplaced: Boolean = false,
    val memberCardBackgroundUri: String? = null,
    val memberCardBackgroundBlurRadius: Int = 0,
    val memberCardBackgroundScalePercent: Int = 100,
    val memberCardBackgroundRotationDegrees: Int = 0,
    val memberCardBackgroundOffsetXPermille: Int = 0,
    val memberCardBackgroundOffsetYPermille: Int = 0,
    val isMemberCardSizeAdjusted: Boolean = false,
    val memberCardWidthDp: Int = 0,
    val memberCardHeightDp: Int = 0,
    val isMemberCardOperationHidden: Boolean = false,
    val isMemberCardBenefitHidden: Boolean = false,
    val isMemberCardFirstBenefitHidden: Boolean = false,
    val isMemberCardSecondBenefitHidden: Boolean = false,
    val isMemberCardThirdBenefitHidden: Boolean = false,
    val isMemberCardBenefitBarHidden: Boolean = false,
    val isMemberCardSvipLevelHidden: Boolean = false,
    val isMemberCardSvipStatusHidden: Boolean = false,
    val isMemberCardRenewButtonHidden: Boolean = false,
    val isIntlMemberCardSvipLevelHidden: Boolean = false,
    val isIntlMemberCardUpgradeButtonHidden: Boolean = false,
    val isMemberCardClickRemoved: Boolean = false,
    val isMemberCardBackgroundViewedOnClick: Boolean = false,
    val isFollowSystemNightModeEnabled: Boolean = false,

    // Performance optimize
    val isPerformanceOptimizeEnabled: Boolean = false,
    val isIntlSplashStartupAccelerateEnabled: Boolean = false,
    val isGarbageCleanServiceRegisterDisabled: Boolean = false,
    val isDatapackSocketRegisterDisabled: Boolean = false,
    val isAigcBackgroundComponentDisabled: Boolean = false,
    val isDynamicPluginAutoDownloadDisabled: Boolean = false,
    val isOemPushServiceDisabled: Boolean = false,
    val isVideoAdPreloadDisabled: Boolean = false,
    val isAdSdkInitDisabled: Boolean = false,
    val isSwanPreloadDisabled: Boolean = false,
    val isThumbnailOperatorServiceDisabled: Boolean = false,
    val isIncentiveBusinessServiceDisabled: Boolean = false,
    val isMediaBrowserServiceAutostartDisabled: Boolean = false,
    val isIconResourceDownloadDisabled: Boolean = false,
    val isB2fGuidancePrefetchDisabled: Boolean = false,
    val isIntlOfflinePackageInitBlocked: Boolean = false,
    val isIntlFeedPreloadDelayed: Boolean = false,
    val isIntlTaskScoreRefreshDelayed: Boolean = false,
    val isIntlStoryDouyinInitBlocked: Boolean = false,
    val isIntlNonCoreDiffSocketDelayed: Boolean = false,
    val isIntlFloatViewStartupDelayed: Boolean = false,
    val isIntlAudioCircleStartupShowBlocked: Boolean = false,
    val isIntlAigcWidgetBackgroundBlocked: Boolean = false,
    val isIntlAlbumAiInitBlocked: Boolean = false,

    // Bottom bar customization
    val isBottomBarCustomEnabled: Boolean = false,
    val isBottomBarTabFileHidden: Boolean = false,
    val isBottomBarTabShareHidden: Boolean = false,
    val isBottomBarTabVipHidden: Boolean = false,
    val isBottomBarTabAigcHidden: Boolean = false,
    val isBottomBarTabHomeHidden: Boolean = false,
    val isBottomBarTabMineHidden: Boolean = false,

    // Restricted features
    val areRestrictedFeaturesUnlocked: Boolean = false,
)
